In [1]:
import pandas as pd
import numpy as np

# Data Loading

In [2]:
datos_clima =  pd.read_pickle("etlData/datos_clima.pickle")
datos_clima

,Temp_Air_Mean,Temp_Air_Min,Temp_Air_Max,Relat_Hum_Mean,Relat_Hum_Min,Relat_Hum_Max,Wind_Speed_Mean,Wind_Speed_Min,Wind_Speed_Max
Date,,,,,,,,,
2017-01-05 19:00:00-05:00,24.00,21.39,29.39,85.0,64.0,96.0,1.03,0.00,3.08
2017-01-06 19:00:00-05:00,22.67,21.11,27.00,85.0,67.0,92.0,2.32,0.09,5.72
2017-01-07 19:00:00-05:00,22.56,19.78,26.61,86.0,67.0,96.0,1.03,0.00,5.90
2017-01-08 19:00:00-05:00,22.44,20.22,25.89,83.0,70.0,92.0,1.70,0.00,5.72
2017-01-09 19:00:00-05:00,23.89,20.72,31.78,76.0,48.0,90.0,1.97,0.00,5.72
...,...,...,...,...,...,...,...,...,...
2023-11-24 19:00:00-05:00,26.00,21.00,32.00,51.0,47.0,91.0,2.00,1.00,3.00
2023-11-25 19:00:00-05:00,25.00,22.00,28.00,65.0,65.0,84.0,2.00,2.00,3.00
2023-11-26 19:00:00-05:00,25.00,22.00,30.00,57.0,57.0,85.0,2.00,1.00,3.00
2023-11-27 19:00:00-05:00,26.00,22.00,33.00,49.0,49.0,90.0,2.00,1.00,3.00
2023-11-28 19:00:00-05:00,23.00,22.00,26.00,68.0,68.0,83.0,2.00,1.00,2.00

In [3]:
producciones =  pd.read_pickle("etlData/producciones.pickle")
producciones

         Cantidad       Fecha Id_Area      Variedad
32 2021   14792.0  2021-11-29    None  Tommy Atkins
   2020   11464.0  2020-12-02    None  Tommy Atkins
   2022   11420.0  2022-12-21    None  Tommy Atkins
   2023    9072.0  2023-11-30    None  Tommy Atkins
30 2020   11497.0  2020-12-03    None  Tommy Atkins
   2021   13805.0  2021-12-04    None  Tommy Atkins
   2022    9019.0  2022-11-30    None  Tommy Atkins
   2023    8848.0  2023-12-01    None  Tommy Atkins
33 2020    1677.0  2020-12-04    None       Ataulfo
   2021    2907.0  2021-11-28    None       Ataulfo
   2022    1350.0  2022-12-03    None       Ataulfo
   2023    1450.0  2023-12-03    None       Ataulfo

In [4]:
datos_clima_promedios =  pd.read_pickle("etlData/datos_clima_promedios.pickle")
datos_clima_promedios

Empty DataFrame
Columns: [Temp_Air_Mean, Temp_Air_Min, Temp_Air_Max, Relat_Hum_Mean, Relat_Hum_Min, Relat_Hum_Max, Wind_Speed_Mean, Wind_Speed_Min, Wind_Speed_Max]
Index: []

# Prep before training

In [5]:
import pickle as pkl

with open("./variablesSeleccionadas.pkl", "rb+") as f:
    variables_seleccionadas = pkl.loads(f.read())
variables_seleccionadas

{'Tommy Atkins': array(['Wind_Speed_Mean', 'Relat_Hum_Max', 'Relat_Hum_Mean',
        'Wind_Speed_Min'], dtype=object),
 'Ataulfo': array(['Wind_Speed_Mean', 'Relat_Hum_Max', 'Relat_Hum_Mean'], dtype=object)}

In [6]:
#x = datos_clima.resample("Y").mean().drop(["Temp_Air_Mean"], axis=1)
x_tommy = datos_clima.resample("Y").mean()[variables_seleccionadas["Tommy Atkins"]]
x_tommy = x_tommy.loc["2020-01-01":"2023-12-31"]
x_tommy

,Wind_Speed_Mean,Relat_Hum_Max,Relat_Hum_Mean,Wind_Speed_Min
Date,,,,
2020-12-31 00:00:00-05:00,1.311385,95.285319,80.083102,0.000000
2021-12-31 00:00:00-05:00,0.634953,96.000000,82.473354,0.000000
2022-12-31 00:00:00-05:00,1.228739,92.366762,67.209169,0.467593
2023-12-31 00:00:00-05:00,1.554217,89.397590,55.328313,1.096386

In [7]:
x_ataulfo = datos_clima.resample("Y").mean()[variables_seleccionadas["Ataulfo"]]
x_ataulfo = x_ataulfo.loc["2020-01-01":"2023-12-31"]
x_ataulfo

                           Wind_Speed_Mean  Relat_Hum_Max  Relat_Hum_Mean
Date
2020-12-31 00:00:00-05:00         1.311385      95.285319       80.083102
2021-12-31 00:00:00-05:00         0.634953      96.000000       82.473354
2022-12-31 00:00:00-05:00         1.228739      92.366762       67.209169
2023-12-31 00:00:00-05:00         1.554217      89.397590       55.328313

In [8]:
y = producciones[["Cantidad", "Variedad"]]
y

         Cantidad      Variedad
32 2021   14792.0  Tommy Atkins
   2020   11464.0  Tommy Atkins
   2022   11420.0  Tommy Atkins
   2023    9072.0  Tommy Atkins
30 2020   11497.0  Tommy Atkins
   2021   13805.0  Tommy Atkins
   2022    9019.0  Tommy Atkins
   2023    8848.0  Tommy Atkins
33 2020    1677.0       Ataulfo
   2021    2907.0       Ataulfo
   2022    1350.0       Ataulfo
   2023    1450.0       Ataulfo

In [9]:
y_tommy = y[y["Variedad"] == "Tommy Atkins"]["Cantidad"]\
    .groupby(producciones["Fecha"].apply(lambda f: f[:4])).mean()
y_tommy

Fecha
2020    11480.5
2021    14298.5
2022    10219.5
2023     8960.0
Name: Cantidad, dtype: float64

In [10]:
y_ataulfo = y[y["Variedad"] == "Ataulfo"]["Cantidad"]#.values
y_ataulfo

33  2020    1677.0
    2021    2907.0
    2022    1350.0
    2023    1450.0
Name: Cantidad, dtype: float64

# Model Training

## Decision trees

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
# Create Decision Tree classifer object
linear_regressor_tommy = LinearRegression().fit(x_tommy, y_tommy)
linear_regressor_tommy

LinearRegression()

In [13]:
# Create Decision Tree classifer object
linear_regressor_ataulfo = LinearRegression().fit(x_ataulfo, y_ataulfo)
linear_regressor_ataulfo

LinearRegression()

In [20]:
from sklearn.model_selection import cross_val_score, LeaveOneOut

def compute_metrics(model, x, y, metric):
    return cross_val_score(model, x, y, cv=LeaveOneOut(), scoring=metric)

In [21]:
vars_tommy = [linear_regressor_tommy, x_tommy, y_tommy]
vars_ataulfo = [linear_regressor_ataulfo, x_ataulfo, y_ataulfo]

metrics = pd.DataFrame(
    #columns=["Variedad","RMSE","MAE","MAPE"]
    [
        {
            "variedad": "Tommy Atkins",
            "RMSE": np.mean(-compute_metrics(*vars_tommy, "neg_mean_squared_error")),
            "MAE": np.mean(-compute_metrics(*vars_tommy, "neg_mean_absolute_error")),
            "MAPE": np.mean(-compute_metrics(*vars_tommy, "neg_mean_absolute_percentage_error")),
        },
        {
            "variedad": "Ataulfo",
            "RMSE": np.mean(-compute_metrics(*vars_ataulfo, "neg_mean_squared_error")),
            "MAE": np.mean(-compute_metrics(*vars_ataulfo, "neg_mean_absolute_error")),
            "MAPE": np.mean(-compute_metrics(*vars_ataulfo, "neg_mean_absolute_percentage_error")),
        },
    ]
)
metrics

       variedad          RMSE          MAE      MAPE
0  Tommy Atkins  2.043236e+06  1090.297015  0.093837
1       Ataulfo  6.175796e+06  1976.687199  1.116937

In [22]:
import os
import pickle

os.makedirs("models", exist_ok=True)
pickle.dump(linear_regressor_tommy, open("models/linear_regressor_tommy.pickle", "wb"))
pickle.dump(linear_regressor_ataulfo, open("models/linear_regressor_ataulfo.pickle", "wb"))